<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - Class com.heliopolis.p3x972.spock.springboot.demo.service.ThingServiceSpec</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>Class com.heliopolis.p3x972.spock.springboot.demo.service.ThingServiceSpec</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/com.heliopolis.p3x972.spock.springboot.demo.service.html">com.heliopolis.p3x972.spock.springboot.demo.service</a> &gt; ThingServiceSpec</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">10</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">0</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.211s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox success" id="successRate">
<div class="percent">100%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Tests</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="success">add existing - toggle off!</td>
<td class="success">0.008s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">add existing - toggle on!</td>
<td class="success">0.002s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">add(Thing(id=3, name=Vulcan, updateDate=2020-10-30T10:30:17.845935))</td>
<td class="success">0.011s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">add(Thing(id=4, name=Dune, updateDate=2020-10-30T10:30:17.846045))</td>
<td class="success">0.003s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get() - does not exist in dev!</td>
<td class="success">0.036s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get() - does not exist in prod!</td>
<td class="success">0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get() - does not exist in qa!</td>
<td class="success">0.001s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get(0) - TARDIS: [Stuff(value=sonic screwdriver), Stuff(value=The Doctor), Stuff(value=Bad Wolf)]</td>
<td class="success">0.149s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get(1) - Holocron: [Stuff(value=Jedi), Stuff(value=Sith)]</td>
<td class="success">0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">get(2) - Omega 13: [Stuff(value=Never give up!), Stuff(value=Never surrender!)]</td>
<td class="success">0.001s</td>
<td class="success">passed</td>
</tr>
</table>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="http://www.gradle.org">Gradle 6.6.1</a> at Nov 1, 2020, 10:30:17 AM</p>
</div>
</div>
</body>
</html>
